-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 19:59:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema leadersacademy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leadersacademy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leadersacademy` DEFAULT CHARACTER SET latin1 ;
USE `leadersacademy` ;

-- -----------------------------------------------------
-- Table `leadersacademy`.`JoiningType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`JoiningType` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `leadersacademy`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`Location` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(300) NULL DEFAULT NULL,
  `Contact` VARCHAR(20) NULL DEFAULT NULL,
  `GeoCoordinates` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `leadersacademy`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`Role` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `leadersacademy`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`Team` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Contact` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `leadersacademy`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`Users` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Password` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `FirstName` VARCHAR(45) NULL DEFAULT NULL,
  `LastName` VARCHAR(45) NULL DEFAULT NULL,
  `RoleId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC),
  INDEX `FK_User_Role_idx` (`RoleId` ASC),
  CONSTRAINT `FK_User_Role`
    FOREIGN KEY (`RoleId`)
    REFERENCES `leadersacademy`.`Role` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `leadersacademy`.`Workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`Workshop` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `LocationId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Workshop_Location_idx` (`LocationId` ASC),
  CONSTRAINT `Workshop_Location`
    FOREIGN KEY (`LocationId`)
    REFERENCES `leadersacademy`.`Location` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `leadersacademy`.`WorkshopDates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leadersacademy`.`WorkshopDates` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `WorkshopId` INT(11) NULL DEFAULT NULL,
  `Day` DATETIME NULL DEFAULT NULL,
  `StartTime` VARCHAR(5) NULL DEFAULT NULL,
  `EndTime` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `WorkshopDates_Workshop_idx` (`WorkshopId` ASC),
  CONSTRAINT `WorkshopDates_Workshop`
    FOREIGN KEY (`WorkshopId`)
    REFERENCES `leadersacademy`.`Workshop` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

USE `leadersacademy` ;

-- -----------------------------------------------------
-- procedure CreateWorkShopDates
-- -----------------------------------------------------

DELIMITER $$
USE `leadersacademy`$$
CREATE DEFINER=`awsdbpb`@`%` PROCEDURE `CreateWorkShopDates`(IN WorkshopId INT,
IN WorkshopDay VARCHAR(200), IN StartTime VARCHAR(5), IN EndTime VARCHAR(5))
BEGIN
	INSERT INTO WorkshopDates(WorkshopId, Day, StartTime, EndTime)
    VALUES (WorkshopId, STR_TO_DATE(WorkshopDay, '%d-%m-%Y'), StartTime, EndTime);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CreateWorkshop
-- -----------------------------------------------------

DELIMITER $$
USE `leadersacademy`$$
CREATE DEFINER=`awsdbpb`@`%` PROCEDURE `CreateWorkshop`(IN LocationId INT)
BEGIN
	INSERT INTO Workshop(LocationId) VALUES(LocationId);
    SELECT LAST_INSERT_ID();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure GetWorkshop
-- -----------------------------------------------------

DELIMITER $$
USE `leadersacademy`$$
CREATE DEFINER=`awsdbpb`@`%` PROCEDURE `GetWorkshop`()
BEGIN
	SELECT w.Id, l.Name, wd.Day
      FROM Workshop w
      JOIN Location l ON w.LocationId = l.Id
      JOIN WorkshopDates wd ON wd.WorkshopId = w.Id
      ORDER BY Day DESC;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
